---
- hosts: web
  gather_facts: no
  tasks:
    - name: Ensure docker.io package present
      apt:
        name: docker.io
        state: present

    - name: create build directory
      file:
        path: /tmp/buildDoker
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: /tmp/buildDoker/Dockerfile
        owner: root
        group: root
        mode: '0644'

    - name: build container image
      docker_image:
        name: tomcat1:v1
        source: build
        build:
          path: /tmp/buildDoker
        state: present

    - name: Login DockerHub
      docker_login:
        username: agolubkov
        password: dckr_pat_l9y81ahvdQ90YWqYCj4LZv-zLkA

    - name: Tag and push to docker hub
      docker_image:
        name: tomcat1:v1
        repository: agolubkov/tomcat1:v1
        push: yes
        source: local

#    - name: archive container image as a tarball
#      docker_image:
#        name: democontainer:v1.0
#        archive_path: /root/democontainer_v1_0.tar
#        source: pull
#        state: present
#
#    - name: fetch archived image
#      fetch:
#        src: /root/democontainer_v1_0.tar
#        dest: ./democontainer_v1_0.tar
#        flat: true

- hosts: db
  gather_facts: no
  tasks:
    - name: Ensure docker.io package present
      apt:
        name: docker.io
        state: present

#    - name: copy tarball to host
#      copy:
#        src: ./democontainer_v1_0.tar
#        dest: /root/democontainer_v1_0.tar

#   - name: load container from tarball
#      docker_image:
#        name: democontainer:v1.0
#        load_path: /root/democontainer_v1_0.tar
#        state: present
#        source: load

    - name: Push Docker image
      docker_image:
        name: tomcat1:v1
        image: agolubkov/tomcat1:v1
        pull:

    - name: RunDockerContainer
      docker_container:
        name: democontainer
        image: democontainer:v1.0
        exposed_ports:
          - 8080
        ports:
          - "8080:8080"
        state: started