---
- name: Build app
  hosts: web

  tasks:
  - name: Ensure python3-pip package present
    apt:
      name: python3-pip
      state: present

  tasks:
  - name: Install Docker Module for Python
    pip:
      name: docker

  tasks:
  - name: Build docker
    docker_image:
      name: tomcat:9-jdk11
      build: 
        dockerfile: ./Dockerfile

#  tasks: Docker
#  docker_container:
#    name: maven 
#    image: maven:3.8.8-eclipse-temurin-8-alpine
#    command: 